name: lego
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.10
  - pytorch
  - lightning
  - numpy
  - jupyterlab
  - jaxtyping
  - ca-certificates
  - openssl
  - certifi
  - imageio
  - einops
  - tensorboardx
  - matplotlib
